# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2eaa68120eeebf651876cde5f17e7408554f4b797ed53a2a20766372cf307e82d6b6cb50ae0f88ab5357e1e42db77576beb665000bedfa55ba3443ef8b32ca28

test:
  secret_key_base: 36f725d95621c2c85c9c83019519ab27d607a0c398d2050c298bec9330a5f00dedcead16fbd3e46b53886fcd5ab3a1d6c38e0dce749d65eacb9621587ee563ff

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
